### ISSUE TITLE
virtual/libgudev-9999 is wrong and breaking users' systems

### ISSUE THREAD

**Issue by benkohler** [batekman/trash-overlay#2]
The dependencies on virtual/libgudev-9999 are wrong.  Please look at versions in portage to see how it should be.  It needs to depend on a specific older set of udev versions, OR the split libgudev package.

Furthermore, you have yours marked STABLE so unsuspecting users get this breakage without looking for it.  Please fix.  Or just remove the package from your overlay.

Thanks

**Comment by benkohler** [comment]
Please also fix or unkeyword virtual/udev-9999 and virtual/libudev-9999

**Comment by batekman** [comment]
Thank you for your note.

I have removed all ebuilds for virtual category and also I have removed sys-fs/eudev-1.1 ebuild because it is too old version to keep.

See https://github.com/batekman/trash-overlay/commit/43ca161c84ed74fce9d6bdc2661fb0711f86deda
